image: ubuntu:18.04

before_script:
  - apt-get update
  - apt-get install -y texlive-xetex texlive-fonts-recommended texlive-font-utils

build:
  stage: build
  script:
    - xelatex dylan-resume.tex
  artifacts:
    path:
      - .